### ISSUE TITLE
Bare except in the Maybe monad

### ISSUE THREAD

**Issue by ckp95** [jasondelaat/pymonad#1]
I'm investigating whether to use this package and I'm concerned about the behaviour of the `Maybe` monad. It has bare try/excepts in its `map` and `bind` methods, so all Exceptions are ignored and converted to `Nothing`. This means if you have a chain of functions you might get a `Nothing` out the end, with no way to figure out what happened. It looks the same no matter if it was a benign/expected error case like a user ID not being present in a database, or something more catastrophic like a `MemoryError`.

Wouldn't it make more sense to reserve this behaviour only for the `Either` monad, since that way at least the Exception is logged and can be inspected afterwards? I would have thought `Maybe` is for representing potential "missingness" not potential "errorness".

**Comment by jasondelaat** [comment]
Good points!

Many introductions to Maybe present it as a basic error handling mechanism but you're correct that the semantics are more about potential "missingness" as you put it. Often we determine that something is missing by intercepting an error (IndexError, KeyError, whatever) but yeah, it really just means a value is missing or not available.
 
I'll try to have a look at it this weekend if I have some time or feel free to make a pull request if you want.

**Comment by jasondelaat** [comment]
Okay, I've removed the try clauses in bind and map for Maybe and changed to tests to make sure that actual errors are not being masked. Should be good now.
