### ISSUE TITLE
Suggestions for flatten or flat map

### ISSUE THREAD

**Issue by mhwenovo** [jasondelaat/pymonad#16]
I would like to ask for some directions how to achieve flatten or flat map functionality. Typical case List of nested Maybe, which we would like to flatten to flat list of Maybe.

**Comment by jasondelaat** [comment]
If I'm interpreting your question correctly you have a list of values inside of a Maybe and you want to convert that to a list of Maybe values? If that's correct then you can do that like so:

```python
from pymonad.maybe import Just, Nothing
from pymonad.list import ListMonad

maybe_list = Just(ListMonad(1, 2, 3, 4, 5))
list_of_maybe = maybe_list.maybe([], lambda l: l.map(Just))
print(list_of_maybe)

maybe_list = Nothing
list_of_maybe = maybe_list.maybe([], lambda l: l.map(Just))
print(list_of_maybe)
```

Or if you're just using normal python lists you could do it like this:
```python
maybe_list = Just([1, 2, 3, 4, 5])
list_of_maybe = maybe_list.maybe([], lambda l: list(map(Just, l)))
print(list_of_maybe)

maybe_list = Nothing
list_of_maybe = maybe_list.maybe([], lambda l: list(map(Just, l)))
print(list_of_maybe)
```

The `maybe` method takes two parameters, the first is a default value which is returned if the Maybe is Nothing. The second is a function which is applied to the value inside of the Maybe value.

If that's not what you meant then I'm not sure I understand your question. If you could give me an example of what you're trying to do I'll be happy to help.

**Comment by mhwenovo** [comment]
If we have a ListMonad with Just like:
x1 = ListMonad(Just(Just(1)), Just(2), Nothing)
for example something like this:
y1 = x1.flatmap(lambda a: a)  #which usually is equal to flatten()
print(y1)
 [Just 1, 2]
will unbox and operate on those which are not Nothing, so for example in such a common case:
x2 = ListMonad(Just(1), Just(2), Nothing, Just(3))
y2 = x1.flatten()
print(y2)
 [1,2,3]

**Comment by jasondelaat** [comment]
Hi, sorry for taking so long to get back to you!
So for the first example, there's not really a way to tackle this particular problem in a general sort of way. Although it's not enforced by python, pymonad pretty much assumes that you're going to be working on lists that are homogeneous. So if every element was nested to the same level, like your second example, then we could work with it in a predictable way. But with things mixed at different nesting levels it gets tricky to write a function that will work for any case without breaking.

It's worth noting that in pure functional languages, like Haskell, the first example you gave wouldn't even be a valid list.
``` haskell
[Just Just 1, Just 2, Nothing] -- I don't think this will even compile in Haskell!
```

But this is python not haskell so you can certainly attempt it. The ideal solution, for your first example, would be to rework whatever code is producing those lists so it does the unnesting first. You can do that with the `join()` method.

``` python
Just(Just(9)).join() # == Just(9)
```

Your second example though we can handle by combining a `map` and a `filter`. `ListMonad` doesn't have a `filter` method but maybe I should add one. In the meantime, we can use python's `filter` function.

``` python
from pymonad.maybe import Just, Nothing
from pymonad.list import ListMonad
from pymonad.tools import identity

def flatten(lst):
    l1 = lst.map(lambda m: m.maybe(None, identity)
    l2 = filter(lambda a: a is not None, l1)
    return ListMonad(*l2)

x = ListMonad(Just(1), Just(2), Nothing, Just(3))
print(flatten(x))    # [1, 2, 3]
```

Hope that helps.

**Comment by mhwenovo** [comment]
Thanks. Let's close this ticket.
