### ISSUE TITLE
Option builder

### ISSUE THREAD

**Issue by PyAntony** [jasondelaat/pymonad#17]
Hi,

can we get a method to build an Option from value or None? something like
```python
maybe: Nothing = Option.build(None)
maybe: Some = Option.build(10)
```

function could be something like:
```python
build = lambda value: value != None and Some(value) else Nothing
```
Or Perhaps just adding the logic inside Some?
```python
def Some(value) -> Option[T]:
    return Option(value, True) if value != None else Nothing
```

I have found myself writing this logic multiple times. Other Options (in other programming languages) have this method built in.

**Comment by jasondelaat** [comment]
Hey! Sorry I took so long to get back to you!
I'm not sure I like the idea of having it built-in to Some directly — I'm sure someone out there for some reason has decided that Some(None) is a perfectly sensible value — and I don't quite like the idea of adding methods that aren't really related to the functioning of the monad type proper.

It's not a bad idea in general though so I propose adding a function under pymonad.tools which can do this for whatever types (Maybe, Option, Either, etc.) Something like:

``` python
@curry(3)
def builder(if_none, otherwise, value):
    if value is None:
        return if_none
    else:
        return otherwise(value)

option_builder=builder(Nothing, Some)

print(option_builder(None))
print(option_builder(42))

either_builder=builder(Left('None value not valid'), Right)

print(either_builder(None))
print(either_builder(42))
```

I think that's an alright general solution, would it solve your problem?

I'm not a huge fan of the name 'builder' because I don't think it really describes the purpose of the function but I'm having trouble coming up with anything better. I'm open to suggestions.

**Comment by PyAntony** [comment]
Hi, thanks for reply.

Well, I didn't know that Some(None) is actually useful. If so then it makes sense to have this functionality separated. As per your solution it's totally fine, name could be anything, perhaps "monad_builder" or "monad_from"?

**Comment by jasondelaat** [comment]
Well, to be fair, I'm pretty sure that Some(None) almost certainly _isn't_ useful but people do strange things. And if somebody somewhere is doing something strange and it's working for them, I don't want to break it. Mostly though, this solution lets people decide for themselves which monads can take None as a sensible value and it means I don't have to add a bunch of special cases into the code for each individual monad to accommodate allowing None or not.

Anyway, I'll need to write this up, add some tests and documentation but I should be able to get it out today or tomorrow after work. Thanks for the suggestion.

**Comment by ckp95** [comment]
Dictionaries offer both an in-band and out-of-band way of signalling missingness. `my_dict.get(key)` uses in-band signalling: if the `key` is missing, it returns `None` by default. But `None` is also a valid value in a dictionary, so this is ambiguous. For that reason, the main way people access dicts is with the square bracket syntax, which raises an out-of-band `KeyError` exception if the key is not in the dict.

The Option monad is another way of doing out-of-band signalling, an alternative to exceptions. So, reasoning by analogy, I think it must be the case that `Some(None)` is meaningful and should be allowed.

**Comment by PyAntony** [comment]
Good explanation!

**Comment by jasondelaat** [comment]
Okay, so I ended up calling it `monad_from_none_or_value` which I recognize is a bit of a mouthful but `builder` didn't seem to get at what the function was actually doing. Anyway, it's curried exactly as in my example above you so can do

``` python
option_builder = monad_from_none_or_value(Nothing, Some)
```

and then just use `option_builder` throughout the rest of your code.

**Comment by PyAntony** [comment]
this is great, thank you!

**Comment by jasondelaat** [comment]
No worries, happy to help. I'll let you close the issue if you're happy with the solution. Thanks again for the suggestion.
